### PR TITLE
Changes Behaviour Of Pick So Undefined Elements Are Omitted

### PR DESCRIPTION
**Pull request by svozza**
As discussed in issue #195 , this pull request brings Highland's _.pick function more in line with other utility libraries.

### CODE REVIEW

**Comment by vqvu** [comment]
Can you change the logic so that the check is on whether or not the key exists and not whether or not the value is `undefined`?

For instance, in lodash
```javascript
require('lodash').pick({id: undefined}, 'id')
// => { id: undefined }
```

In your PR

```javascript
_([{id: undefined}])
    .pick('id')
    .toArray(console.log);
// => [{}]
```

**Comment by svozza** [comment]
Yeah, that makes more sense. Done and added some documentation around the behaviour too.

**Comment by vqvu** [comment]
Nice. Looks good to me.

One final thing, can you rebase on top of caolan/master so we get a bit nicer history? Something like

```
$ git remote add caolan https://github.com/caolan/highland
$ git fetch caolan
$ git rebase caolan/master
$ git push -f
```

**Comment by svozza** [comment]
Done!

**Comment by vqvu** [comment]
@svozza Looks like you added some new commits. Is this good to go now?

**Comment by svozza** [comment]
Yep, all done now.

**Comment by vqvu** [comment]
Ok. Merging this since we have agreement from @jeromew in #195.

**Pull request merged**
