### PR TITLE
Implements done, modifies each to return a stream

### PR DESCRIPTION
**Pull request by LewisJEllis**
A proposal for `.done()` as discussed in #54 and #55.

This modifies `.each` so that, instead of returning undefined, it returns a stream that ends after the return of the last call of the iterator.

Done is then derived from `toArray`, with the special `.ended` check for cases like:

    _([1,2,3]).each(function (x) {
        // do something
    }).done(function () {
        // do something else
    });

where `each` will have already ended due to its synchronous source.

### CODE REVIEW

**Comment by dweinstein** [comment]
:+1:

**Comment by ralphtheninja** [comment]
Hi! This is excellent. Lets merge it :)

**Comment by vqvu** [comment]
@LewisJEllis can you rebase onto the current master? Is this ready to merge?

There is a 3.x potential tag, but we can support this now and the eventual #172 `onDestroy` eventually right?

**Comment by LewisJEllis** [comment]
Sure thing; sorry for the delay here. This is potentially ready to merge, but I'm not really up to speed on the related conversations that have been going on. The 3.x potential tag was because of the considerations that @jeromew brought up, but I think #172 reached a consensus that addresses those.

**Comment by vqvu** [comment]
I'll merge this. We have consensus on the back propagate of `nil`, and there's no reason to hold this up.

**Pull request merged**
