### PR TITLE
Adds sort stream transformation incl. tests

### PR DESCRIPTION
**Pull request by svozza**
As mentioned in #169

adds noValueErrorTest for sort

split sort into sort and sortBy

### CODE REVIEW

**Comment by svozza** [comment]
Does anyone have time to take a look at this? Would be good to get rid of one of the last 6+ month old PRs.

**Comment by quarterto** [comment]
This looks good. Something to think about is that this buffers the entire stream before sorting; we *could* do an online insertion sort, but it's a speed/memory tradeoff: insertion sort would use O(n²) memory but do the sort while streaming which is probably more efficient.

I think we should go ahead with this pull request and maybe revisit this in the future with benchmarks.

**Comment by svozza** [comment]
Yeah, we could build up the sorted array with a binary insert or something. Could definitely be a nice way of doing it if the benchmarks warrant it.

**Comment by quarterto** [comment]
On the other hand, I trust the build-in sort much better than anything I could write.

I'll go ahead and merge this.

**Pull request merged**
