### PR TITLE
add favicon, fixes #322

### LINKED ISSUE #322: Favicon for the doc pages.

### PR DESCRIPTION
**Pull request by quarterto**
highland 32 highland 16

/cc @caolan, what do you think?

### CODE REVIEW

**Comment by svozza** [comment]
Nice!

**Comment by caolan** [comment]
sure, I like it :)

**Comment by quarterto** [comment]
Gonna go ahead and merge this, and run the `gh-pages` task manually.

**Comment by quarterto** [comment]
screenshot 2015-06-25 11 53 57
screenshot 2015-06-25 11 54 51

**Pull request merged**
