### PR TITLE
Keep context in wrapCallback (and use wrapCallback in streamifyAll)

### PR DESCRIPTION
**Pull request by quarterto**
As discussed in #247

### CODE REVIEW

**Comment by svozza** [comment]
Good stuff, although do we want to mention the functionality in the docs or maybe just even give an example.

**Comment by quarterto** [comment]
Although this is, strictly speaking, a breaking change, since it's something I think `wrapCallback` should always have done I'm happy to consider it a bugfix?

**Comment by svozza** [comment]
Agreed, I think that's reasonable.

**Comment by quarterto** [comment]
Ok, merging.

**Pull request merged**
