### PR TITLE
Remove testling to fix Greenkeeper nodeunit upgrade branch

### PR DESCRIPTION
**Pull request by svozza**

### CODE REVIEW

**Comment by quarterto** [comment]
Testling-ci is dead anyway, so +1

**Comment by svozza** [comment]
I wonder should we look at Sauce Labs or something similar? I've heard it's a bit finicky to set up though.

**Comment by quarterto** [comment]
Seems less painful with [Zuul](https://github.com/defunctzombie/zuul/wiki/cloud-testing)?

**Comment by svozza** [comment]
Yeah, it does but it doesn't look like they have support for Nodeunit. :(

**Comment by quarterto** [comment]
Oh. I assumed it was test-framework-agnostic :disappointed:

**Comment by svozza** [comment]
I think you can extend it yourself but I don't know how much work that is.

**Comment by LewisJEllis** [comment]
I have some experience with Sauce Labs; it's not too bad to set up, although I'm not sure specifically about Travis integration. I can put something together if we're interested.

**Comment by svozza** [comment]
Yeah, that would be brilliant!

**Pull request merged**
