### PR TITLE
_checkBackPressure should cancel any repeated consume (Fixes #325).

### LINKED ISSUE #325: Sorted Merge (Help Needed)
I'm having a bit of difficulty implementing a transform that merges an arbitrary number of sorted streams. I hacked around a bit with the `zipAll` implementation but for some reason only the first element of the sorted stream gets emited when I call `each` (`toArray` doesn't even produce output). However, I know that the function emits the rest of the items in the correct order because if I put some `console.log` statements in I can track the elements as they're processed. Here's what I have so far  (apologies for the code dump):

```javascript
function sortedMergeBy(pred, streams) {
    var buffer = [];

    return _(streams).collect().flatMap(function (srcs) {

        function nextValue(index, src, push, next) {
            src.pull(function (err, x) {
                if (err) {
                    push(err);
                    nextValue(index, src, push, next);
                }
                else if (x === _.nil) {
                    // push last element in buffer
                    push(null, buffer[index]);
                    // must be final stream
                    if (srcs.length === 1) {
                        push(null, _.nil);
                    }
                    else {
                        // remove stream from list of streams to be
                        // pulled from and remove corresponding index in
                        // buffer
                        buffer.splice(index, 1);
                        srcs.splice(index, 1);
                        next();
                    }
                }
                else {
                    // buffer now contains an element from each stream
                    if (buffer.length === srcs.length) {
                        push(null, buffer[index]);
                    }
                    // replace old buffer value with new one, using the same index
                    buffer[index] = x;
                    next();
                }
            });
        }

        if (!srcs.length) {
            return _([]);
        }

        return _(function (push, next) {
            // need to buffer first element of all streams first before 
            // beginning comparisons
            if (buffer.length < srcs.length) {
                for (var i = 0, length = srcs.length; i < length; i++) {
                    nextValue(i, srcs[i], push, next);
                }
            }
            // apply comparison function to find index in buffer of
            // element to push
            var pair = buffer.reduce(function (memo, item, idx) {
                return pred(item, memo[1]) ? [idx, item] : memo;
            }, [0, buffer[0]]);
            // index of element in buffer allows us to know which stream to pull from
            nextValue(pair[0], srcs[pair[0]], push, next);
        });
    });
};
```
Here's the output of running it:

```javascript
var arr = [8, 20, 303, 304, 555, 666];
var arr2 = [3, 4, 5, 6, 77, 88];
var arr3 = [77, 89, 97 ,1000, 1100, 1200];
var arr4 = [6, 7, 8, 9, 10, 11];
var arr5 = [13, 17, 18, 19, 111, 211];

var xs = [_(arr), _(arr2), _(arr3), _(arr4), _(arr5)];

sortedMergeBy(function(a, b) {
    return b > a;
}, xs).each(_.log); //=> 3
```
Is there anything obvious I'm doing wrong here?

### PR DESCRIPTION
**Pull request by vqvu**
This seems to fix the issue @svozza found in #325, but I'm not too confident in it.

Fortunately, the 3.x engine doesn't have this bug, so we should be OK long-term.

### CODE REVIEW

**Comment by svozza** [comment]
Poor v2, really creaking at the seams now! Out of interest, why are you unsure of how well this will work?

**Comment by vqvu** [comment]
Because the fix that I wanted to make was

```diff
diff --git a/lib/index.js b/lib/index.js
index 5ce4fd9..297cd6e 100755
--- a/lib/index.js
+++ b/lib/index.js
@@ -824,7 +824,8 @@ Stream.prototype.resume = function () {
                 this.emit('drain');
             }
         }
-    } while (this._repeat_resume);
+    } while (this._repeat_resume && !this.paused);
+    this._repeat_resume = false;
     this._resume_running = false;
 };
```

But this broke stream redirection for some reason, and that's the one part of the v2 engine that I don't fully understand. v3 was written because the interplay between `_checkBackPressure` and stream redirection was too complex for me to grok.

**Comment by vqvu** [comment]
Also, the fact that you need to mess with `_repeat_resume` outside of the `resume` function seems a bit sketchy to me.

**Comment by svozza** [comment]
Well, it might not be the optimal solution but it's still preferable to what we have now.

**Pull request merged**
