### PR TITLE
Add tap alias with tests

### LINKED ISSUE #109: tap?
It feels like _.tap is missing (map without the need to remember to return?)

### PR DESCRIPTION
**Pull request by svozza**
Resolves #109

### CODE REVIEW

**Comment by vqvu** [comment]
We need a more DRY way to write tests for aliases...

But for now, merged!

**Comment by quarterto** [comment]
Something like

```js
function testAliae(aliae, fn) {
  aliae.forEach(function(alias) {
    exports[alias] = function(test) {
      fn(_[alias], test);
    };
  });
}

testAliae(['tap', 'doto'], function(tap, test) { /*...*/ });
```
?

**Comment by svozza** [comment]
Yeah, agreed. I might actually have a chance to look at that tonight.

And on the topic of DRY I wonder is there anything that can be done about error/stream ending logic that litters the majority of `consume` functions:

```javascript
if (err) {
            push(err);
            next();
        }
        else if (x === nil) {
            push(err, x);
        }
```

**Comment by quarterto** [comment]
Like a wrapper around `consume` that takes care of that automatically?

**Comment by vqvu** [comment]
@quarterto yeah, except somehow make it work with the prototype functions too, so that we can use the chaining syntax.

**Comment by svozza** [comment]
I was even just thinking of pulling it out into a separate function but actually a wrapper sounds like a cleaner way to do it.

**Comment by vqvu** [comment]
I just thought of something...can't we just have a test that verifies the equality of the aliases methods? Like

```javascript
test.strictEqual(_.tap, _.doto);
test.strictEqual(_([]).tap, _([]).doto);
```

**Comment by svozza** [comment]
Actually yeah, that's a much better idea and it's how the `sequence` alias is tested. I've created a new PR, more so that other people can see the pattern if they have to do this.

**Pull request merged**
