### PR TITLE
Added Sort as of Issue #50

### PR DESCRIPTION
**Pull request by snnd**
As discussed in issue #50 here is the pull request for sort()
https://github.com/caolan/highland/issues/50

Regards,
Dennis

### CODE REVIEW

**Comment by LewisJEllis** [comment]
Since this got mentioned recently - @snnd, can you break this up? You can refer to `split`/`splitBy` or `uniq`/`uniqBy` for examples. I'd also be glad to take it over if you don't have time/interest :)

**Comment by svozza** [comment]
@snnd Like #11 there's not very much left on this to do so I was wondering if you minded me finishing this pull request on your behalf? I've pulled in all your changes onto a branch of my own and tidied everything up so everything is basically good to go.

**Comment by svozza** [comment]
I'm guessing @snnd is busy with other work looking at his Github stats for this year so I'm going to push ahead with this one anyway. The original issue that prompted this PR has been open for more than a year so it'd be nice to close it.

**Comment by snnd** [comment]
Sorry for being IDLE for a while too long now. I would be glad to see someone continuing this PR for me.

Cheers,
Dennis

**Comment by svozza** [comment]
No probs, you still get full credit in the commit history, I just squashed your commits into one with some light changes.

**Comment by quarterto** [comment]
Closing in favour of #245.

**Pull request closed without merging**
