### PR TITLE
Fantasy Land compatibility?

### PR DESCRIPTION
**Pull request by quarterto**
[Fantasy Land](https://github.com/fantasyland/fantasy-land) is a specification for algebraic Javascript structures. Highland streams almost implement Monoid and Monad. What we'd need to change to be fully compatible:
1. Alias `flatMap` to `chain`
2. Add `_.of` as a shortcut for `λ x → _([x])`
3. Add `_.empty` as a shortcut for `λ → _([])`
4. Add `ap`, to apply each of a stream of functions to each of a stream of values.
5. (Nice to have) add tests to ensure we satisfy the laws.

What are people's opinions on this?

### CODE REVIEW

**Comment by quarterto** [comment]
Here's the work in progress, I'll flesh out the tests, remove the non-fantasy-check ones I added and implement `ap`, then it should be ready to go. Think it makes sense to leave this unmerged until 3.0 lands.

**Comment by svozza** [comment]
Can this be closed now because of the recent PRs @amsross has done?

**Comment by amsross** [comment]
I would say so. All the mentioned bases are covered in #643, #657, and #658.

**Comment by svozza** [comment]
Cool, I'll close then.

**Pull request closed without merging**
