### PR TITLE
Modifies pipe to pass along highland errors

### PR DESCRIPTION
**Pull request by LewisJEllis**
Discussions on 3.0.0 have mentioned #166 a few times, so here it is on the 3.0.0 branch.

### CODE REVIEW

**Comment by LewisJEllis** [comment]
Yes; it's not a huge behavior change, but there definitely might be uses that this would trip.

I consider it ready to merge, but there haven't been any comments on the matter since the discussion in #136, so I've left it open.

**Comment by ibash** [comment]
Anyway we can get this backported to 2? I saw the discussion in #166 but I still think it's wrong expectation and at worse awkward that connecting two highland streams via pipe does not propagate errors.

**Comment by LewisJEllis** [comment]
I agree it's silly, but simple of a change as it is, it strictly speaking is a non-BC as far as semver is concerned. I don't think we should merge it on 2.x, but there could be other options.

**Comment by ibash** [comment]
Grumble, fair enough, might make a utility to do it then.



-- 
Islam Sharabash
islam.sharabash@gmail.com
217-377-9657

**Comment by svozza** [comment]
I agree it's not ideal but with the fix gone into `through` there's really no reason to ever use `pipe` to join two Highland streams.

**Comment by ibash** [comment]
@svozza use case is I want to pass a stream to a function and have it write to it.
e.g.

```
stream = _() ...;

writeDataToStream(stream);
```

Inside of `writeDataToStream` it needs to do something like:
```
function writeDataToStream(stream) {
  stream2 = ...;

  stream2.pipe(stream);
}
```

Is there a better way to do that?

**Comment by vqvu** [comment]
Why can't you have this? The point of streams is that you can construct the stream objects synchronously even if the data source isn't. What specifically requires you to ever write a `writeDataToStream` function?

```javascript
function getDataAsStream() {
    var stream2 = ...;
    return stream2;
}

// Same ... used in your example above to construct the stream
var stream = getDataAsStream() ...;
```

**Comment by ibash** [comment]
You're right -- should be able to do that. Was just thinking about it as:
1. Build a pipeline
2. Push data down the pipeline

But it makes just as much sense as 
1. Get your datasource
2. Build a pipeline

**Comment by vqvu** [comment]
OK. Since we have #240 now, and we seem to have consensus, I'll go ahead and close this as unnecessary.

**Comment by LewisJEllis** [comment]
@vqvu you originally closed this as unnecessary thanks to #240, and I just trusted your judgment, but @svozza still wants it as per recent discussion on #179. I'm not sure what the situation is but maybe you guys could discuss whether this is necessary?

**Pull request closed without merging**
