### PR TITLE
support drop(), issue #11

### PR DESCRIPTION
**Pull request by alexbeletsky**
Provides support for `.drop()`

### CODE REVIEW

**Comment by alexbeletsky** [comment]
Yes, I'm still willing to help and make this PR happen!

**Comment by svozza** [comment]
What's the status of this? Do we even need it now that we have transducers?

**Comment by vqvu** [comment]
We don't *need* it, but I think we should have it as a pair with `take`.

**Comment by svozza** [comment]
Yep, it makes sense to have the both of them. 

@alexbeletsky There's not very much left on this to do so I grabbed the changes from your pull request using the [hub](https://hub.github.com) tool and I can make the minor adjustments for you. Do you mind if I finish this pull request on your behalf? It's just it's been open for a while and it would be nice to close it.

**Comment by alexbeletsky** [comment]
@svozza please, go ahead! Thanks a lot for your help, if any question plz ping me.

**Comment by svozza** [comment]
No probs!

**Comment by vqvu** [comment]
Superseded by #244.

**Pull request closed without merging**
