### PR TITLE
Fix linting related issues

### PR DESCRIPTION
**Pull request by jonboiser**
This is a big one! Just saw #230 and #236 and thought it would be easy enough to help out with.

Adding the indent rule and fixing the lints in `lib` was pretty simple.

I then when through the whole test suite, breaking it up by the particular lint.

I left three lints alone since they were pretty prevalent in the code, and may be there for good reasons.

Amazingly, all the tests still pass, although I saw a few deprecation notices.

### CODE REVIEW

**Comment by jonboiser** [comment]
And amazingly, CI passed!

**Comment by vqvu** [comment]
Oh wow. Thanks! Fixing the tests must have been a lot of work. Can you remove the `es6` environment though? We don't transpile, so the code should be pure es3. ES6 features (like `Set`, `Map`, etc) must be explicitly guarded.

**Comment by jonboiser** [comment]
I got rid of the 'es6' env and just registered Map and Set as globals in test.js through a comment. Does that work?

**Comment by vqvu** [comment]
Yes, please use `global.Map` instead.

**Comment by jonboiser** [comment]
Made the change.

**Comment by vqvu** [comment]
Great. Thanks!

**Pull request merged**
