### PR TITLE
asyncMap.

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by quarterto** [comment]
I'm -1 on this. Just use `flatMap`.

**Comment by vqvu** [comment]
Yep. This is equivalent to

```javascript
s.map(f).map(_);
// or
s.map(_.compose(_, f));
```

I don't think it really needs to be included in the library.

**Comment by ronag** [comment]
`flatMap` won't work since it doesn't wrap the result in a `_`. Maybe that could be changed?

**Comment by vqvu** [comment]
Conceptually, `flatMap` is an important operator in allowing arbitrary streams transforms. Imagine if `Promise#then` doesn't wait on promises returned from the handlers! Most operators that we provide can be implemented via `flatMap`, including `map` and `sequence`. The fact that it's actually implemented in the reverse is simply an implementation detail, and I'd argue that many more people would be upset if we removed `flatMap` than if we removed `sequence`.

`asyncMap` just doesn't seem to have that kind of utility.

**Pull request closed without merging**
